def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('register', '/api/v1/users/register')
    config.add_route('login', '/api/v1/users/login')
    config.add_route('create_product', '/api/v1/users/products')
    config.add_route('get_product', '/api/v1/users/products/{id}')
    config.add_route('create_cart', '/api/v1/users/carts')
    config.add_route('get_carts', '/api/v1/users/carts')
    config.add_route('get_cart', '/api/v1/users/carts/{id}')
    config.add_route('update_cart', '/api/v1/users/carts/{id}')
    config.add_route('delete_cart', '/api/v1/users/carts/{id}')
    config.add_route('create_order', '/api/v1/users/orders')
    config.add_route('get_orders', '/api/v1/users/orders')
    config.add_route('get_order', '/api/v1/users/orders/{id}')
    config.add_route('update_order', '/api/v1/users/orders/{id}')
    config.add_route('delete_order', '/api/v1/users/orders/{id}')